project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "trainingMM"
  site-url: "google"
  repo-url: google

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; UW-Madison, 2025"

  sidebar:
    # logo: "images/openscapes_hex.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/AparicioJohan/trainingMM
        text: "GitHub repository"

    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Welcome
      - section: "Starting LM"
        contents:
          - href: pages/00_start_lm.html
            text: ANOVA and fixed effects
          - href: pages/01_predict_LM.qmd
            text: Marginal means (SE)
          - href: pages/02_QR_decomp.html
            text: QR decomposition in LM
          - href: pages/04_covariates_LM.html
            text: Covariates in LM
          - href: pages/99_404.html
            text: Other software
      - section: "Starting LMM"
        contents:
          - href: pages/05_MVN.html
            text: Multivariate Normal
          - href: pages/03_LMM.html
            text: Mixed model by hand
          - href: pages/06_Heritabilities.html
            text: Heritability
          - href: pages/03.1_predict_LMM.html
            text: Predictions in LMM
          - href: pages/99_404.html
            text: Outliers LMM
      - section: "Parametrizations"
        contents:
          - href: pages/08_Parametrizations.html
            text: Breeding vs Genotypic
          - href: pages/08_Parametrizations.html
            text: Polyploids and Digenic Dominance
      - section: "Advanced LMM"
        contents:
          - href: pages/99_404.html
            text: Genotype-by-environment
          - href: pages/99_404.html
            text: Factor analytic models
          - href: pages/99_404.html
            text: Two-stage analysis
      - href: about.html
        text: About

format:
  html:
    theme: cosmo
    code-copy: true
    code-overflow: wrap
    toc: true
